### ISSUE TITLE
NoSuchMethodException: sun.misc.IOUtils.readAllBytes  on java 8

### ISSUE THREAD

**Issue by liqunl** [AdoptOpenJDK/bumblebench#27]
Works with jdk 10 and jdk 14, but not java 8
```
java -jar BumbleBench.jar StringEqualsBench
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.misc.IOUtils.readAllBytes(java.io.InputStream)
	at net.adoptopenjdk.bumblebench.core.Util.<clinit>(Util.java:44)
Caused by: java.lang.NoSuchMethodException: sun.misc.IOUtils.readAllBytes(java.io.InputStream)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at net.adoptopenjdk.bumblebench.core.Util.<clinit>(Util.java:36)
```
java version
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```

**Comment by smlambert** [comment]
@kusumachalasani - I see that https://github.com/AdoptOpenJDK/bumblebench/pull/23 introduced sun.misc.IOUtils.readAllBytes so tagging you here.
